Repository felipementel/PotatoStore, pull requests merged in 2022-08, with the labels that each got.

#5 fix: update docker-compose file v3.1
  docker-compose/infra-on-docker.yml
Labels: bug

#11 feat: end point GetAll
  .github/workflows/dotnet-estudo.yml
  docker-compose/infra-on-docker.yml
  src/Potato.Product.Api/Controllers/ProductController.cs
  src/Potato.Product.Api/Converters/DateOnlyConverter.cs
  src/Potato.Product.Api/Program.cs
  src/Potato.Product.Application/AppServices/ProductAppService.cs
  src/Potato.Product.Application/Dtos/ProductDto.cs
  src/Potato.Product.Application/Interfaces/Services/IProductAppService.cs
  src/Potato.Product.Domain/Aggregates/Products/Entities/Product.cs
  src/Potato.Product.Domain/Aggregates/Products/Entities/URL.cs
  src/Potato.Product.Domain/Aggregates/Products/Interfaces/Services/IProductService.cs
  src/Potato.Product.Domain/Aggregates/Products/Services/ProductService.cs
  src/Potato.Product.Infra.Database/ProductContext.cs
  src/Potato.Product.Infra.Database/Repositories/ProductRepository.cs
Labels: enhancement

#14 Delete
  docker-compose/infra-on-docker.yml
  src/Potato.Product.Api/Controllers/ProductController.cs
  src/Potato.Product.Application/AppServices/ProductAppService.cs
  src/Potato.Product.Application/Dtos/ProductDto.cs
  src/Potato.Product.Application/Interfaces/Services/IProductAppService.cs
  src/Potato.Product.Domain/Aggregates/Products/Entities/Product.cs
  src/Potato.Product.Domain/Aggregates/Products/Interfaces/Repositories/IProductRepository.cs
  src/Potato.Product.Domain/Aggregates/Products/Interfaces/Services/IProductService.cs
  src/Potato.Product.Domain/Aggregates/Products/Services/ProductService.cs
  src/Potato.Product.Infra.Database/Migrations/ProductContextModelSnapshot.cs
  src/Potato.Product.Infra.Database/Repositories/ProductRepository.cs
Labels: enhancement, good first issue
